version: '3'
services:
  vscode:
    platform: linux/amd64
    image: vscode-webui
    ports:
      - "8080:8080"
      - "2222:22"
    volumes:
      - /home/${USER}/Documents/projects/containers/vscode/projects:/home/${USER}/projects
